# This file is for custom makefile variable at the project level.
# They are meant to be share by the whole project team.

APP_VERSION := 0.0.0
APPLICATION_NAME := building_operation_with_cobs
CONDA_ENVIRONMENT := building-op-cobs-env
PYTHON_VERSION := 3.11